# partially based on https://github.com/joerick/cibuildwheel/blob/master/examples/github-deploy.yml

on: [push, pull_request]

jobs:
  win_mac_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Build wheels
        run: setup.py bdist_wheel

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  linux_wheels:
    name: Build wheels on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Build manylinux Python wheels
        uses: RalfG/python-wheels-manylinux-build@v0.3.3-manylinux2010_x86_64
        with:
          python-versions: 'cp38-cp38'
          pip-wheel-args: '-w ./wheelhouse'

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  publish:
    name: Publish to PyPI
    needs: [win_mac_wheels,linux_wheels, build_sdist]
    runs-on: ubuntu-latest

    # only publish if new release
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
