name: Checks

on: [push, pull_request]

# thanks red or wherever you got it from
jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          - "3.8"
        tox_env:
          # style-black, style-isort, lint-flake8, type-mypy
          - style-black
          - style-isort
          - lint-flake8
        include:
          - tox_env: style-black
            friendly_name: Style (black)
          - tox_env: style-isort
            friendly_name: Style (isort)
          - tox_env: lint-flake8
            friendly_name: Lint (flake8)

      fail-fast: false

    name: Tox - ${{ matrix.friendly_name }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.ref }}
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: "Run tox: ${{ matrix.friendly_name }}"
        env:
          TOXENV: ${{ matrix.tox_env }}
        run: |
          tox

  pyright:
    name: Pyright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install Red-DiscordBot types-tabulate types-cachetools asyncache data-science-types

      - name: Run pyright
        uses: jakebailey/pyright-action@v1
