name: Lint and quality

on: [push, pull_request]

jobs:
  quality-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@v1.3.0
        with:
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: true
          use-mypy: false
          use-isort: true
          extra-flake8-options: "--ignore E501,F401,W503"
          extra-black-options: "--line-length 120"
          extra-isort-options: "--line-length 120 --trailing-comma"
